### PR TITLE
HTML formatter

### PR DESCRIPTION
**Pull request by lgommans**
Still a bunch of stuff I'd like to do, big and small, like supporting IP addresses in the URL parser or improving the index page (which is currently unsorted), but a line has to be drawn somewhere. I think this makes a good first version of the HTML formatter.

### CODE REVIEW

**Comment by tvdstaaij** [comment]
While reviewing the files I noticed that has mixed spaces/tabs indenting, and the html/css files are all tabs. Could you change all indenting to two spaces for project-wide consistency?

One more technical issue that I failed to notice before: when you read copy/files from the data directory, this is implicitly done relative to the working directory of the process rather than the filesystem location of the actual script files. So it will crash if the working directory does not equal the project directory. To solve this you can use `File.expand_path` with `__FILE__` like [on this line](https://github.com/tvdstaaij/telegram-history-dump/blob/4dd1c5817a844b0df2464278aed621d33450adc3/telegram-history-dump.rb#L151) (the `...` may be a bit counter-intuitive, it counts the filename as a level in the hierarchy I believe). Now this also made me realize that I made the very same mistake on the dev branch, so that's another v2.0.0 bug fixed (2b0c943) :)

**Comment by lgommans** [comment]
Done. Calling the program from outside of its directory does not work though, it fails when trying to `require` the html formatter. I added the `expand_path` calls though, but couldn't test whether it works outside of the project dir. Inside it works from anywhere (e.g. in `/output` or `/formatters` I can call `../telegram-history-dump.rb` just fine).

**Comment by tvdstaaij** [comment]
>Calling the program from outside of its directory does not work though, it fails when trying to require the html formatter.

That was the issue I mentioned here

>Now this also made me realize that I made the very same mistake on the dev branch, so that's another v2.0.0 bug fixed (2b0c943)

But you didn't pull this commit yet, it should work after doing so. I can't test right now but it looks good, so I'll merge it now.

**Comment by lgommans** [comment]
> That was the issue I mentioned here

Oh right, forgot that.

Thanks for all the effort you're putting into this! :)

**Pull request merged**
