### PR TITLE
Add loop_video option to the html formatter

### PR DESCRIPTION
**Pull request by gorlug**
When set to true this option will add autoplay and loop options to video
tags. That way video gifs will be displayed the same as in the telegram
client.

### CODE REVIEW

**Comment by tvdstaaij** [comment]
Shouldn't this only apply to video, i.e. `if $config['formatters']['html']['loop_video'] && filetype == 'video'`? I think the results are going to be pretty interesting when this option is enabled for a dialog that contains audio files, heh.

**Comment by gorlug** [comment]
Oh you are right, that would be bad.

**Comment by gorlug** [comment]
Now that I think about it, videos with sound would also not be so good. Would it start to become overkill if one would use e.g. ffmpeg to check if the video has an audio stream?

**Comment by gorlug** [comment]
Of course a far easier solution is to simply set looped videos to muted. This makes sure that there is no unwanted audio playing. If a video has audio you want to hear it can simply be unmuted.

**Comment by gorlug** [comment]
@tvdstaaij I squashed all commits into one if you would like to accept the pull request

**Comment by tvdstaaij** [comment]
I'll take another look at this when I have time, sorry for leaving it open this long.

**Comment by tvdstaaij** [comment]
Looks good, sorry again for stalling this.

**Comment by gorlug** [comment]
No problem! Thank you!

**Pull request merged**
